// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UBYS.Data;

#nullable disable

namespace ubys.Migrations
{
    [DbContext(typeof(UbysDbContext))]
    partial class UbysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UBYS.Models.Akademisyen", b =>
                {
                    b.Property<long>("AkademisyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AkademisyenId"));

                    b.Property<string>("AkademisyenAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AkademisyenAdres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AkademisyenCinsiyet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("AkademisyenDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("AkademisyenEposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AkademisyenSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AkademisyenTc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("AkademisyenTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("BolumId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unvan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AkademisyenId");

                    b.HasIndex("AkademisyenEposta")
                        .IsUnique();

                    b.HasIndex("AkademisyenTc")
                        .IsUnique();

                    b.HasIndex("BolumId");

                    b.ToTable("Akademisyenler");

                    b.HasData(
                        new
                        {
                            AkademisyenId = 1L,
                            AkademisyenAd = "Hakan",
                            AkademisyenAdres = "Beşiktaş / İstanbul",
                            AkademisyenCinsiyet = "Erkek",
                            AkademisyenDogumTarihi = new DateTime(1978, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AkademisyenEposta = "hakan.gunes@ornekuni.edu.tr",
                            AkademisyenSoyad = "Güneş",
                            AkademisyenTc = "24449676978",
                            AkademisyenTelefon = "05339990001",
                            AktifMi = true,
                            BolumId = 1L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Unvan = "Prof. Dr."
                        },
                        new
                        {
                            AkademisyenId = 2L,
                            AkademisyenAd = "Ebru",
                            AkademisyenAdres = "Sarıyer / İstanbul",
                            AkademisyenCinsiyet = "Kadın",
                            AkademisyenDogumTarihi = new DateTime(1985, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AkademisyenEposta = "ebru.tekin@ornekuni.edu.tr",
                            AkademisyenSoyad = "Tekin",
                            AkademisyenTc = "42492946718",
                            AkademisyenTelefon = "05339990002",
                            AktifMi = true,
                            BolumId = 1L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Unvan = "Doç. Dr."
                        },
                        new
                        {
                            AkademisyenId = 3L,
                            AkademisyenAd = "Cem",
                            AkademisyenAdres = "Maltepe / İstanbul",
                            AkademisyenCinsiyet = "Erkek",
                            AkademisyenDogumTarihi = new DateTime(1983, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AkademisyenEposta = "cem.yavuz@ornekuni.edu.tr",
                            AkademisyenSoyad = "Yavuz",
                            AkademisyenTc = "75359841260",
                            AkademisyenTelefon = "05339990003",
                            AktifMi = true,
                            BolumId = 3L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Unvan = "Dr. Öğr. Üyesi"
                        });
                });

            modelBuilder.Entity("UBYS.Models.Bolum", b =>
                {
                    b.Property<long>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BolumId"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BolumAdres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BolumEposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BolumTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FakulteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BolumId");

                    b.HasIndex("BolumEposta")
                        .IsUnique();

                    b.HasIndex("FakulteId");

                    b.ToTable("Bolumler");

                    b.HasData(
                        new
                        {
                            BolumId = 1L,
                            AktifMi = true,
                            BolumAdi = "Bilgisayar Mühendisliği",
                            BolumAdres = "A Blok 3. Kat",
                            BolumEposta = "bilgisayar@ornekuni.edu.tr",
                            BolumTelefon = "02124440201",
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FakulteId = 1L
                        },
                        new
                        {
                            BolumId = 2L,
                            AktifMi = true,
                            BolumAdi = "Makine Mühendisliği",
                            BolumAdres = "A Blok 2. Kat",
                            BolumEposta = "makine@ornekuni.edu.tr",
                            BolumTelefon = "02124440202",
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FakulteId = 1L
                        },
                        new
                        {
                            BolumId = 3L,
                            AktifMi = true,
                            BolumAdi = "Matematik",
                            BolumAdres = "B Blok 2. Kat",
                            BolumEposta = "matematik@ornekuni.edu.tr",
                            BolumTelefon = "02124440203",
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FakulteId = 2L
                        },
                        new
                        {
                            BolumId = 4L,
                            AktifMi = true,
                            BolumAdi = "İşletme",
                            BolumAdres = "C Blok 1. Kat",
                            BolumEposta = "isletme@ornekuni.edu.tr",
                            BolumTelefon = "02124440204",
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FakulteId = 3L
                        });
                });

            modelBuilder.Entity("UBYS.Models.Fakulte", b =>
                {
                    b.Property<long>("FakulteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FakulteId"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FakulteAd")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FakulteAdres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FakulteEposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FakulteTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KisaAd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FakulteId");

                    b.HasIndex("FakulteEposta")
                        .IsUnique();

                    b.ToTable("Fakulteler");

                    b.HasData(
                        new
                        {
                            FakulteId = 1L,
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FakulteAd = "Mühendislik Fakültesi",
                            FakulteAdres = "Merkez Kampüs A Blok",
                            FakulteEposta = "muhendislik@ornekuni.edu.tr",
                            FakulteTelefon = "02124440101"
                        },
                        new
                        {
                            FakulteId = 2L,
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FakulteAd = "Fen-Edebiyat Fakültesi",
                            FakulteAdres = "Merkez Kampüs B Blok",
                            FakulteEposta = "fenedebiyat@ornekuni.edu.tr",
                            FakulteTelefon = "02124440102"
                        },
                        new
                        {
                            FakulteId = 3L,
                            AktifMi = true,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            FakulteAd = "İktisadi ve İdari Bilimler Fakültesi",
                            FakulteAdres = "Güney Kampüs C Blok",
                            FakulteEposta = "iibf@ornekuni.edu.tr",
                            FakulteTelefon = "02124440103"
                        });
                });

            modelBuilder.Entity("UBYS.Models.Kullanici", b =>
                {
                    b.Property<long>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KullaniciId");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("UBYS.Models.Ogrenci", b =>
                {
                    b.Property<long>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OgrenciId"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<long>("BolumId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenciAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgrenciAdres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OgrenciCinsiyet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("OgrenciDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("OgrenciEposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OgrenciSinif")
                        .HasColumnType("int");

                    b.Property<string>("OgrenciSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgrenciTc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("OgrenciTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OgrenciId");

                    b.HasIndex("BolumId");

                    b.HasIndex("OgrenciEposta")
                        .IsUnique();

                    b.HasIndex("OgrenciTc")
                        .IsUnique();

                    b.ToTable("Ogrenciler");

                    b.HasData(
                        new
                        {
                            OgrenciId = 1L,
                            AktifMi = true,
                            BolumId = 1L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciAd = "Ayşe",
                            OgrenciAdres = "Bağcılar / İstanbul",
                            OgrenciCinsiyet = "Kadın",
                            OgrenciDogumTarihi = new DateTime(2003, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciEposta = "ayse.yilmaz@ogr.ornekuni.edu.tr",
                            OgrenciSinif = 3,
                            OgrenciSoyad = "Yılmaz",
                            OgrenciTc = "42950115298",
                            OgrenciTelefon = "05321110001"
                        },
                        new
                        {
                            OgrenciId = 2L,
                            AktifMi = true,
                            BolumId = 1L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciAd = "Mehmet",
                            OgrenciAdres = "Kadıköy / İstanbul",
                            OgrenciCinsiyet = "Erkek",
                            OgrenciDogumTarihi = new DateTime(2004, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciEposta = "mehmet.demir@ogr.ornekuni.edu.tr",
                            OgrenciSinif = 2,
                            OgrenciSoyad = "Demir",
                            OgrenciTc = "21199630090",
                            OgrenciTelefon = "05321110002"
                        },
                        new
                        {
                            OgrenciId = 3L,
                            AktifMi = true,
                            BolumId = 2L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciAd = "Zeynep",
                            OgrenciAdres = "Üsküdar / İstanbul",
                            OgrenciCinsiyet = "Kadın",
                            OgrenciDogumTarihi = new DateTime(2002, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciEposta = "zeynep.kaya@ogr.ornekuni.edu.tr",
                            OgrenciSinif = 4,
                            OgrenciSoyad = "Kaya",
                            OgrenciTc = "26706917794",
                            OgrenciTelefon = "05321110003"
                        },
                        new
                        {
                            OgrenciId = 4L,
                            AktifMi = true,
                            BolumId = 3L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciAd = "Emre",
                            OgrenciAdres = "Beylikdüzü / İstanbul",
                            OgrenciCinsiyet = "Erkek",
                            OgrenciDogumTarihi = new DateTime(2005, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciEposta = "emre.sahin@ogr.ornekuni.edu.tr",
                            OgrenciSinif = 1,
                            OgrenciSoyad = "Şahin",
                            OgrenciTc = "39294742426",
                            OgrenciTelefon = "05321110004"
                        },
                        new
                        {
                            OgrenciId = 5L,
                            AktifMi = true,
                            BolumId = 4L,
                            CreatedDate = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciAd = "Gülşah",
                            OgrenciAdres = "Ataşehir / İstanbul",
                            OgrenciCinsiyet = "Kadın",
                            OgrenciDogumTarihi = new DateTime(2003, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OgrenciEposta = "gulsah.ozturk@ogr.ornekuni.edu.tr",
                            OgrenciSinif = 3,
                            OgrenciSoyad = "Öztürk",
                            OgrenciTc = "30202008634",
                            OgrenciTelefon = "05321110005"
                        });
                });

            modelBuilder.Entity("UBYS.Models.Akademisyen", b =>
                {
                    b.HasOne("UBYS.Models.Bolum", "Bolum")
                        .WithMany("Akademisyenler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("UBYS.Models.Bolum", b =>
                {
                    b.HasOne("UBYS.Models.Fakulte", "Fakulte")
                        .WithMany("Bolumler")
                        .HasForeignKey("FakulteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("UBYS.Models.Ogrenci", b =>
                {
                    b.HasOne("UBYS.Models.Bolum", "Bolum")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("UBYS.Models.Bolum", b =>
                {
                    b.Navigation("Akademisyenler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("UBYS.Models.Fakulte", b =>
                {
                    b.Navigation("Bolumler");
                });
#pragma warning restore 612, 618
        }
    }
}
